icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"
player = ["YoutubeMusic", "strawberry", "fooyin", "mpd"]
interface_name_exclude = ["kdeconnect"]
format_alt = " $icon {$combo.str(max_w:15,rot_interval:0.4) |}"
[block.format]
full = " $icon {$combo.str(max_w:30) $prev $next |}"
short = " $icon {$combo.str(max_w:15) $prev $next |}"
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "right"
action = "toggle_format"
[block.theme_overrides]
idle_bg = "#3f4d64"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:23) |"
short = " $title.str(max_w:11) |"
[[block.click]]
button = "left"
cmd = "i3-msg 'floating toggle; [tiling con_id=__focused__] border pixel 3; [floating con_id=__focused__] border normal'"
[block.theme_overrides]
idle_bg = "#39465b"

[[block]]
block = "sound"
driver = "auto"
format = " $icon {$volume.eng(w:2) |}"
max_vol = 250
[block.mappings]
"alsa_output.pci-0000_00_1f.3.pro-output-0" = "Speakers"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#354155"
[block.icons_overrides]
volume_muted = "\ueee8"

[[block]]
block = "net"
interval = 5
format = " $icon ↓:$speed_down.eng(prefix:K)↑:$speed_up.eng(prefix:K) "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"
[block.theme_overrides]
idle_bg = "#2d3749"

[[block]]
block = "weather"
format = " $icon  $temp $wind m/s "
format_alt = "$icon  om 12 timer: {$temp_favg ({$temp_fmin}-{$temp_fmax})|Unavailable} "
[[block.click]]
button = "left"
action = "None"
[[block.click]]
button = "right"
action = "toggle_format"
[block.service]
name = "metno"
coordinates = ["59.9125115", "10.747012"] # Oslo
lang = "nb"
[block.theme_overrides]
idle_bg = "#272f40"
[block.icons_overrides]
weather_fog = "\ue313"
weather_rain = "\uef1c"
#weather_clouds_night = "\ueeef"
weather_clouds_night = "\uf0c2"
weather_rain_night = "\uef1c"
weather_sun = "\ueef0"
weather_fog_night = "\ue346"
weather_snow = "\uf2dc"
weather_thunder_night = "\ue32a"
weather_thunder = "\ue31d"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%d/%m - %R') "
[[block.click]]
button = "left"
cmd = "firefox --no-remote --class cleanwebappfirefoxc1 -profile ~/.mozilla/firefox/npbhnp6z.default calendar.google.com"
[block.theme_overrides]
idle_bg = "#212837"
[block.icons_overrides]
time = "󰥔"

[[block]]
block = "menu"
text = " 󰵆 "
[[block.items]]
display = " &gt; Apps &lt;"
cmd = "rofi -config ~/.config/rofi/launchers/type-1/style-5.rasi -show drun"
[[block.items]]
display = " &gt; Windows &lt;"
cmd = "rofi -config ~/.config/rofi/launchers/type-1/style-005.rasi -show window"
[[block.items]]
display = " &gt; Clipboard &lt;"
cmd = "rofi -config ~/.config/rofi/launchers/type-1/style-05.rasi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}'"
[[block.items]]
display = " &gt; Bluetooth &lt;"
cmd = "blueman-manager"
[[block.items]]
display = " &gt; Calculator &lt;"
cmd = "rofi -config ~/.config/rofi/launchers/type-1/style-5.rasi -show calc"
[block.theme_overrides]
idle_bg = "#191f2a"

#[[block]]
#block = "menu"
#text = " "
#[[block.items]]
#display = " &gt; # &lt;"
#cmd = ":"
#[block.theme_overrides]
#idle_bg = "#191f2a"

[[block]]
block = "menu"
text = " \uf011  "
[[block.items]]
display = " &gt;  Lock  &lt; "
cmd = "~/.config/scripts/power/lock.sh"
[[block.items]]
display = " &gt;  Suspend  &lt; "
cmd = "~/.config/scripts/power/suspend.sh"
[[block.items]]
display = " &gt;  Exit  &lt; "
cmd = "~/.config/scripts/power/exit.sh"
[[block.items]]
display = " &gt;  Reboot  &lt; "
cmd = "~/.config/scripts/power/reboot.sh"
[[block.items]]
display = " &gt;  Shutdown  &lt; "
cmd = "~/.config/scripts/power/poweroff.sh"
[block.theme_overrides]
idle_bg = "#191f2a"
