# https://docs.rs/i3status-rs/latest/i3status_rs/

icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"
player = ["YoutubeMusic", "strawberry", "fooyin", "mpd"]
interface_name_exclude = ["kdeconnect"]
format_alt = " $icon {$combo.str(max_w:6,rot_interval:0.4) |}"
[block.format]
full = " $icon {$combo.str(max_w:14) $prev $next |}"
short = " $icon {$combo.str(max_w:6) $prev $next |}"
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "right"
action = "toggle_format"
[block.theme_overrides]
idle_bg = "#3f4d64"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:12) |"
short = " $title.str(max_w:6) |"
[[block.click]]
button = "middle"
cmd = "i3-msg 'floating toggle; [tiling con_id=__focused__] border pixel 3; [floating con_id=__focused__] border normal'"
[[block.click]]
button = "right"
cmd = "i3-msg 'layout toggle split'"
[block.theme_overrides]
idle_bg = "#39455f"

[[block]]
block = "sound"
driver = "auto"
format = " $icon {$volume.eng(w:2) |}"
max_vol = 200
[block.mappings]
"alsa_output.pci-0000_00_1f.3.pro-output-0" = "Speakers"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.icons_overrides]
volume_muted = "\ueee8"
[block.theme_overrides]
idle_bg = "#2f394f"

[[block]]
block = "weather"
format = " $icon  $temp $wind m/s "
format_alt = "$icon  om 12 timer: {$temp_favg ({$temp_fmin}-{$temp_fmax})|Unavailable} "
[[block.click]]
button = "left"
action = "None"
[[block.click]]
button = "right"
action = "toggle_format"
[block.service]
name = "metno"
coordinates = ["", ""]
lang = "nb"
[block.icons_overrides]
weather_fog = "\ue313"
weather_rain = "\uef1c"
#weather_clouds_night = "\ueeef"
weather_clouds_night = "\uf0c2"
weather_rain_night = "\uef1c"
weather_sun = "\ueef0"
weather_fog_night = "\ue346"
weather_snow = "\uf2dc"
weather_thunder_night = "\ue32a"
weather_thunder = "\ue31d"
[block.theme_overrides]
idle_bg = "#293245"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"
[block.theme_overrides]
idle_bg = "#232b3b"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%d/%m - %R') "
# OPTIONAL:
#[[block.click]]
#button = "left"
#cmd = "firefox --no-remote --class cleanwebappfirefoxc2 -profile ~/.mozilla/firefox/pb5pvlut.webapp-calendar calendar.google.com"
[block.icons_overrides]
time = "󰥔"
[block.theme_overrides]
idle_bg = "#1d2431"

# OPTIONAL:
#[[block]]
#block = "battery"
#format = " $icon $percentage "
#[block.theme_overrides]
#idle_bg = "#171d27"

[[block]]
block = "menu"
text = " 󰵆 "
[[block.items]]
display = " &gt; Clipboard &lt;"
cmd = "rofi -config ~/.config/rofi/launchers/type-1/style-05.rasi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}'"
[[block.items]]
display = " &gt; Apps &lt;"
cmd = "rofi -config ~/.config/rofi/launchers/type-1/style-5.rasi -show drun"
[[block.items]]
display = " &gt; Bluetooth &lt;"
cmd = "blueman-manager"
[block.theme_overrides]
idle_bg = "#171d27"

[[block]]
block = "menu"
text = " 󰹯 "
[[block.click]]
button = "middle"
cmd = "i3-msg mode 'default'"
[[block.items]]
display = " &gt; Empty workspace &lt;"
cmd = "i3-msg workspace number $(~/.config/i3/scripts/new-workspace-monitor2.py)"
[[block.items]]
display = " &gt; Resize mode &lt;"
cmd = "i3-msg mode 'Resize mode'"
[[block.items]]
display = " &gt; Cursor mode &lt;"
cmd = "i3-msg mode 'Cursor mode'"
[block.theme_overrides]
idle_bg = "#171d27"

[[block]]
block = "menu"
text = " \uf011  "
[[block.items]]
display = ""
cmd = ":"
[[block.click]]
button = "left"
cmd = "~/.config/rofi/powermenu/type-1/powermenu.sh"
[[block.click]]
button = "middle"
cmd = "i3-msg restart"
[[block.click]]
button = "right"
cmd = "pkill i3bar && (i3bar -b bar-0 & i3bar -b bar-1 &)"
[block.theme_overrides]
idle_bg = "#171d27"
