[mgr]
linemode = "mtime"
show_hidden = true
sort_reverse = true
sort_by = "mtime"

[preview]
wrap            = "yes"
max_width       = 700
max_height      = 1000

[opener]
edit = [
  { run = 'alacritty -e nvim "$@"', orphan=true, desc = "Open Neovim in new Alacritty", for = "unix" },
  { run = '$EDITOR "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
extract = [
  { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here", for = "unix" },
]

[plugin]
#prepend_preloaders = [
#]
prepend_previewers = [
  # audio metadata
  { mime = "audio/*",   run = "exifaudio"},
]
